<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    public function up(): void
    {
        DB::table('associados')->insert([
            [
                'nome' => 'Kayakeria',
                'slug' => 'kayakeria',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'kayakeria@gmail.com',
                'whatsapp' => 'https://wa.me/5585982095543',
                'instagram' => 'https://instagram.com/kayaqueria',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 3211</p><p><strong>Responsável:</strong> Rafael Medeiros</p><p><strong>Tipos de equipamento:</strong> canoa, caiaque, stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Vibe Vaa Club',
                'slug' => 'vibe-vaa-club',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'vibevaaclub@gmail.com',
                'whatsapp' => 'https://wa.me/5585986080663',
                'instagram' => 'https://instagram.com/vibeaaclub',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 2961 15b Meireles</p><p><strong>Responsável:</strong> Marilia Nobre da Costa</p><p><strong>Tipos de equipamento:</strong> canoa, caiaque, stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'SupFortal',
                'slug' => 'supfortal',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'supfortal@gmail.com',
                'whatsapp' => 'https://wa.me/5585997875260',
                'instagram' => 'https://instagram.com/supfortal',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 3123(em frente ao Hotel Beira Mar)</p><p><strong>Responsável:</strong> Tico</p><p><strong>Tipos de equipamento:</strong> colete, canoa havaina, caiaque duplo e individual, sup, stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Ceará Sup Club',
                'slug' => 'ceara-sup-club',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'cearasupclub@gmail.com',
                'whatsapp' => 'https://wa.me/5585988208212',
                'instagram' => 'https://instagram.com/crarasupclub',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 3958 Sala 06 / Av. Sen Carlos Jereissati, 301 - Antonio Diogo</p><p><strong>Responsável:</strong> Delano Pinheiro / Santiago</p><p><strong>Tipos de equipamento:</strong> canoa, caiaque, stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Taiba VAA',
                'slug' => 'taiba-vaa',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'paroandrade@hotmail.com',
                'whatsapp' => 'https://wa.me/5585986815673',
                'instagram' => 'https://instagram.com/taibavaa',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 2892 (em frente a bebelu)</p><p><strong>Responsável:</strong> Patrícia Rodrigues / Andrade</p><p><strong>Tipos de equipamento:</strong> canoa, caiaque, stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Elione Souza Canoagem',
                'slug' => 'elione-souza-canoagem',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'elionesousa@gmail.com',
                'whatsapp' => 'https://wa.me/5585996678558',
                'instagram' => 'https://instagram.com/escolaelionesousa',
                'content' => '<p><strong>Endereço:</strong> Av. Beira Mar</p><p><strong>Responsável:</strong> Elione</p><p><strong>Tipos de equipamento:</strong> canoa havaiana</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Na Onda',
                'slug' => 'na-onda',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'naonda.sup@gmail.com',
                'whatsapp' => 'https://wa.me/5585999364103',
                'instagram' => 'https://instagram.com/naonda.sup',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 6081 (em frente ao ideal clube)</p><p><strong>Responsável:</strong> Mateus</p><p><strong>Tipos de equipamento:</strong> caiaque e stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Imua Canoa e Club',
                'slug' => 'imua-canoa-e-club',
                'categoria' => 'praia-de-meireles',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'imuaceara@gmail.com',
                'whatsapp' => 'https://wa.me/5585986536817',
                'instagram' => 'https://instagram.com/imuaceara',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 4000</p><p><strong>Responsável:</strong> Aluisio de Miranda / Arcela</p><p><strong>Tipos de equipamento:</strong> canoa havaiana</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Athená Canoagem',
                'slug' => 'athena-canoagem',
                'categoria' => 'praia-do-mucuripe',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'athenacanoagem@gmail.com',
                'whatsapp' => 'https://wa.me/5585991606565',
                'instagram' => 'https://instagram.com/athenacanoagem',
                'content' => '<p><strong>Endereço:</strong> Iate Clube na Av Vicente de Castro 4813 - Cais do Porto</p><p><strong>Responsável:</strong> Thereza</p><p><strong>Tipos de equipamento:</strong> canoa havaina</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Brothers Wind School',
                'slug' => 'brothers-wind-school',
                'categoria' => 'praia-do-mucuripe',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'manelbws@gmail.com',
                'whatsapp' => 'https://wa.me/5585996952837',
                'instagram' => 'https://instagram.com/brotherswinschool',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 4260 - Mucuripe</p><p><strong>Responsável:</strong> Emanuel</p><p><strong>Tipos de equipamento:</strong> caiaque, stand up, winsurfer, laser</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'Hale Kai',
                'slug' => 'hale-kai',
                'categoria' => 'praia-de-iracema',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'halekai.iracema@gmail.com',
                'whatsapp' => 'https://wa.me/5585992508484',
                'instagram' => 'https://instagram.com/halekai_iracema',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 1650 / Rua Bento Albuquerque, 2500 bl 03 apto 408</p><p><strong>Responsável:</strong> Angelita Almeida</p><p><strong>Tipos de equipamento:</strong> canoa havaina</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nome' => 'NoCrazy Paddle',
                'slug' => 'nocrazy-paddle',
                'categoria' => 'praia-de-iracema',
                'type' => 'escolas',
                'imagem' => 'default.png',
                'link' => 'robertaqueirozp@me.com',
                'whatsapp' => 'https://wa.me/5585986229644',
                'instagram' => 'https://instagram.com/nocrazypaddle',
                'content' => '<p><strong>Endereço:</strong> Av Beira Mar 810</p><p><strong>Responsável:</strong> -</p><p><strong>Tipos de equipamento:</strong> caiaque e stand -up</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('associados')
            ->where('type', 'escolas')
            ->whereIn('categoria', ['praia-de-meireles', 'praia-do-mucuripe', 'praia-de-iracema'])
            ->delete();
    }
};
